# Generated by Django 4.0.4 on 2022-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
