# Generated by Django 4.0.4 on 2022-05-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0002_alter_beca_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beca',
            old_name='reqerimientos',
            new_name='requerimientos',
        ),
    ]
